#!/bin/sh
CONFIG_LIBS="-L/opt/otbtf/lib -lgdal"
CONFIG_DEP_LIBS="-lssl -lcrypto -llzma -L/opt/otbtf/lib -lgeotiff -ltiff -ljpeg -lpng -lnetcdf -lhdf5_hl -lhdf5 -ldl -lcurl -ldfalt -lmfhdfalt -lxdr -lopenjp2 -lkmlbase -lkmldom -lkmlengine -lminizip -luriparser -lz -lsqlite3 -lexpat -lxml2 -lgeos_c -lproj -lpthread -lstdc++ -lm"
CONFIG_PREFIX="/opt/otbtf"
CONFIG_CFLAGS="-I/opt/otbtf/include"
CONFIG_DATA="/opt/otbtf/share/gdal"
CONFIG_VERSION="3.6.3"
CONFIG_GNM_ENABLED=yes
CONFIG_FORMATS="JPEG raw GTIFF MEM vrt Derived HFA SDTS NITF GXF AAIGrid CEOS SAR_CEOS XPM DTED JDEM Envisat ELAS FIT L1B RS2 ILWIS RMF Leveller SGI SRTMHGT IDRISI GSG ERS PALSARJaxa DIMAP GFF COSAR PDS ADRG COASP TSX Terragen BLX MSGN TIL R northwood SAGA XYZ ESRIC HF2 KMLSUPEROVERLAY CTG ZMap NGSGEOID IRIS MAP CALS SAFE SENTINEL2 PRF MRF WMTS GRIB BMP TGA STACTA OGCAPI BSB AIGrid ARG USGSDEM AirSAR OZI PCIDSK SIGDEM RIK STACIT PDF PNG GIF WCS HTTP netCDF Zarr DAAS EEDA HDF5 PLMOSAIC WMS HDF4 Rasterlite MBTiles JP2OpenJPEG PCRaster MEM geojson TAB Shape KML VRT AVC GML CSV DGN GMT NTF S57 Tiger Geoconcept GeoRSS DXF PGDump GPSBabel EDIGEO SXF OpenFileGDB WAsP Selafin JML VDV FlatGeobuf MapML SDTS GPX SVG CSW LIBKML PLSCENES WFS NGW Elastic Idrisi PDS SQLite GeoPackage OSM VFK MVT AmigoCloud Carto XLSX CAD ODS LVBAG"
usage()

{
	cat <<EOF
Usage: gdal-config [OPTIONS]
Options:
	[--prefix[=DIR]]
	[--libs]
	[--dep-libs]
	[--cflags]
	[--datadir]
	[--version]
	[--ogr-enabled]
	[--gnm-enabled]
	[--formats]
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

case $1 in
  --libs)
    echo $CONFIG_LIBS
    ;;

  --dep-libs)
    echo $CONFIG_DEP_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --datadir)
    echo $CONFIG_DATA
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --ogr-enabled)
    echo yes
    ;;

  --gnm-enabled)
    echo $CONFIG_GNM_ENABLED
    ;;

  --formats)
    echo $CONFIG_FORMATS
    ;;

  *)
    usage 1 1>&2
    ;;

esac
